version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
  pre_build:
    commands:
      - echo Installing dependencies...
  build:
    commands:
      - echo Running build process...
  post_build:
    commands:
      - echo Build completed successfully!
